# Use new Travis-CI infrastructure
sudo: false

# Source language and JDK version to use
language: java
jdk: oraclejdk8

# Use cached Maven dependencies
cache:
  directories:
    - $HOME/.m2

# Pre-install Maven dependencies
install: mvn dependency:go-offline

# Compile and test source
script: mvn clean -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}

# Fetch resources, run deployment goal/task, and generate Javadocs and reports
after_success:
  # Get files for use with build, namely the custom Maven settings.xml and scripts
  - "git clone https://github.com/flow/travis-ci-resources.git $HOME/build/flow/travis"
  # DEVELOP: Check if commit is not a pull request, if repo is official, if branch is not master; then deploy artifacts
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == flow/network ]] && [[ $TRAVIS_BRANCH == develop ]] && mvn javadoc:jar source:jar deploy --settings $HOME/build/flow/travis/settings.xml"
  # RELEASE: Check if commit is not a pull request, if repo is official, if branch is master; then run deployment script
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == flow/network ]] && [[ $TRAVIS_BRANCH == master ]] && $HOME/build/flow/travis/deploy.sh && $HOME/build/flow/travis/gh-pages.sh"
  # Generate Javadocs and report for Coveralls.io
  - "mvn javadoc:javadoc cobertura:cobertura coveralls:report -DserviceJobId=$TRAVIS_JOB_ID"

# RELEASE: Deploy main JAR to GitHub Releases
deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: "target/flow-network-`cat version.txt`.jar"
  skip_cleanup: true
  on:
    branch: master

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  webhooks:
    # Send build information and status to Notifico
    - http://n.tkte.ch/h/2042/RDqswG16PpWPx1d7RD3Gx7Ka

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
    # Super secure, encrypted variables! Ssssh!
    - secure: "Auu6BiJNEI4K22x5Fskki3/bTSiA0VYqd/5Wh8GE86y/upVCcUAmW8dBBJ0VAIhcQjTBbMhxqP+G0K8DbpD8T+OfMEqZbK4kGOZVPEGZ6sHjKvdlKYlMK5g4r6a6+3hI457mWuXSjr4xQ2ar1dGKgOp+1leYwDHU+24IzSjnTHs="
    - secure: "bs6gZ6YT5Rq0oU0F0YRhPVAEZG1rPTAAz6BjNLW0HPus1NflXYMDIOe2HpnjA++N+1jgiYFiIyBkOWRAu3pyJsBEkf9hpOsnEMQcMddrZpzp+Qa4XogKLSOwbUJQNCkx2bUM/UlC0sk3WoRY0F1OoIoewqfuc7+OnV/klV64hNg="
    - secure: "iUTC++/9GL6FBYQYSPPlgZNbcsVztFzMkD1OAm4gVkTOVGvm8QmkP1JUNTNTJqglgvQg/0AzpSP0XPe173svoaqqPW5aEdQ0hO+wAJ51C7PKqimh5hT2j1MhE6IVsOgkSfSeknXBmrN7pRjDu3xTkS/+aCfpMFU5pBDGVuTqUfo="
    - secure: "hCM+d/tIrfCKPvtUyB7oQ1CBR63HvcU8HAQiSCAI5e9Lu+mGllk0qCU/53sE2OTDoQyAnye4/b1Lim6wLWV4bDpLFyH4uVe/oH9TxCpu1pFROY/wIJNBnrqrp80ZPJfDE1wuYT60gn9J5Om6HtWE3exk7Gz+8kPRx5FzfKEaQo8="
