# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    # Documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/openjdk:8-jdk

    working_directory: ~/network

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          # Use cache for this pom
          - network-{{ checksum "pom.xml" }}
          # Fallback to latest cache is an exact match is not found
          - network-

      - run: mvn -T 2 -B dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: network-{{ checksum "pom.xml" }}

      # Deploy
      - run: mvn -T 2 -B -s .circleci/maven.xml source:jar javadoc:jar deploy

      # Test results
      - store_test_results:
          path: target/surefire-reports
